FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Scarica modello al build!
RUN python3 -c "from transformers import AutoTokenizer, AutoModelForMaskedLM; \
    AutoTokenizer.from_pretrained('opensearch-project/opensearch-neural-sparse-encoding-multilingual-v1'); \
    AutoModelForMaskedLM.from_pretrained('opensearch-project/opensearch-neural-sparse-encoding-multilingual-v1')"

COPY main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]